from fastapi import APIRouter
from backend.models import DocumentRequest, DocumentResponse

# Try to import your actual generator, if fails use simple one
try:
    from backend.ai_core.gemini_generator import GeminiGenerator
    generator = GeminiGenerator()
    USE_GEMINI = True
except Exception as e:
    print(f"Gemini not loaded, using simple template: {e}")
    USE_GEMINI = False
    generator = None

router = APIRouter()

def simple_doc(doc_type, party, req):
    return f"""
LEGAL DOCUMENT: {doc_type.upper()}

BETWEEN:
Party 1: {party}
Party 2: Company

1. PURPOSE / REQUIREMENT:
{req}

2. CONFIDENTIALITY:
All information related to {req} is confidential.

3. TERM: 2 Years

4. SIGNATURE:
______________ 
{party}

Generated by LegalEaseAI
"""

@router.post("/generate", response_model=DocumentResponse)
def generate_document_endpoint(request: DocumentRequest):
    # This will NEVER give AttributeError again
    req_text = getattr(request, 'requirement', None) or getattr(request, 'prompt', None) or getattr(request, 'description', None) or getattr(request, 'details', None) or getattr(request, 'user_prompt', None) or "NDA for startup"
    doc_type = getattr(request, 'document_type', 'NDA')
    party_name = getattr(request, 'party_name', 'lavanya S')

    if USE_GEMINI:
        try:
            # Try different method names
            if hasattr(generator, 'generate_document'):
                result = generator.generate_document(doc_type, party_name, req_text)
            elif hasattr(generator, 'generate'):
                result = generator.generate(doc_type, party_name, req_text)
            else:
                result = simple_doc(doc_type, party_name, req_text)
        except Exception as e:
            print(f"Gemini error {e}, using simple")
            result = simple_doc(doc_type, party_name, req_text)
    else:
        result = simple_doc(doc_type, party_name, req_text)

    return DocumentResponse(document=result, document_type=doc_type)

@router.get("/health")
def health_check():
    return {"status": "Backend Connected! LegalEase API is running successfully"}