from fastapi import APIRouter
from backend.models import DocumentRequest, DocumentResponse
class GeminiDocumentGenerator:
    def generate(self, doc_type: str, prompt: str, party_name: str = "", details: str = ""):
        return f"""
LEGAL DOCUMENT - {doc_type.upper()}
Party: {party_name}
Request: {prompt}
Details: {details}
Draft generated by LegalEaseAI.
"""

    def generate_document(self, document_type: str = "", doc_type: str = "", party_name: str = "", user_prompt: str = "", prompt: str = "", details: str = ""):
        actual_type = document_type or doc_type or "NDA"
        actual_prompt = user_prompt or prompt or ""
        return self.generate(doc_type=actual_type, prompt=actual_prompt, party_name=party_name, details=details)
router = APIRouter()
generator = GeminiDocumentGenerator()

@router.post("/generate", response_model=DocumentResponse)
def generate_document_endpoint(request: DocumentRequest):
    generated_document = generator.generate_document(
        document_type=request.document_type,
        doc_type=request.document_type,
        party_name=request.party_name,
        user_prompt=request.requirement,
        prompt=request.requirement,
        details=request.requirement
    )
    return DocumentResponse(
        document=generated_document,
        document_type=request.document_type
    )